### ISSUE TITLE
Run cli tasks in sequence

### ISSUE THREAD

**Issue by trickpeeraze** [dromejs/drome#27]
I love the idea of drome that try to **minimalize abstraction** but when it comes to complex task scheduling like doing a sequence, those concept was gone.

Easy, I'd like to ask how can I achieve this
```js
{
  build: {
    step1: 'cd /app/src',
    step2: 'npm build',
  }
}
```
in sequence?

_In my real situation, I try to preprocess sass first and then postprocess with postCSS after but I can't._

**Comment by kodipe** [comment]
@trickpeeraze thanks for report the issue :)

Project documentation was wrong - that's why you couldn't run mentioned configuration as sequence. If you want to run tasks in sequence, you should use array notation where array order (I've just fixed documentation - https://drome.js.org/docs/configuration#sequence) e.g.:

```
{
  build: [
    'npm run sass',
    'npm run post-css'
  ]
}
```

Apologize for wrong docs!

**Comment by trickpeeraze** [comment]
Wow great!

It'd be nice if you clearly mention that the task's form supports both **string** as a cli and **function** as javascript execution in the document.

Cheers!
