### ISSUE TITLE
Sequence call as an array instead of object with "first", "second", "third".

### ISSUE THREAD

**Issue by Piotr-Aueternum** [dromejs/drome#3]
IMHO I think it's better to describe it with an array. You don't need to care about naming another property. Just append next task.

**Comment by kodipe** [comment]
Object for sequence and array for parallel tasks seemed ok for me at the beginning. 
Now whenI'm thinking about that unnamed tasks in sequence, should be not bad - especially if we would like to add suppot for passing result from one task to another in a sequence.
Will see.

**Comment by simondell** [comment]
Array structures imply an order, by design. You can see it in the way you address array items: `someArray[n]; someArray[n+1]`. Object structures do not imply order and, AFAIK, the JavaScript spec defines no obligation to preserve the order of the member definitions.

Following these two ideas, I feel the sequence and parallel definitions in Drone use inappropriate structures. In fact, because the spec explicitly defines no obligation to preserve definition order, any working sequence based on object iteration only works by accident.
